apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: payment.events
  namespace: kumarh5149-dev
  labels:
    strimzi.io/cluster: healthshield-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000 # 7 days
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: claim.events
  namespace: kumarh5149-dev
  labels:
    strimzi.io/cluster: healthshield-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: policy.events
  namespace: kumarh5149-dev
  labels:
    strimzi.io/cluster: healthshield-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: underwriting.events
  namespace: kumarh5149-dev
  labels:
    strimzi.io/cluster: healthshield-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000 # 7 days
    segment.bytes: 1073741824

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: analytics.events
  namespace: kumarh5149-dev
  labels:
    strimzi.io/cluster: healthshield-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000 # 7 days
    segment.bytes: 1073741824

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: audit.events
  namespace: kumarh5149-dev
  labels:
    strimzi.io/cluster: healthshield-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000 # 7 days
    segment.bytes: 1073741824

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: claim.dlq.events
  namespace: kumarh5149-dev
  labels:
    strimzi.io/cluster: healthshield-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000 # 7 days
    segment.bytes: 1073741824
