"""
HealthShield Gemini AI Engine
Unified client for Google Gemini models across all HealthShield AI Agents.
Supports Gemini 2.5 / 3.x series models with native function calling,
system instructions, and intelligent offline heuristic fallback.
"""

import json
import os
import urllib.request
import urllib.parse
from typing import Dict, Any, List, Optional
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass


# Model Configurations
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY") or os.getenv("ANTIGRAVITY_API_KEY")
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-pro")
GEMINI_FLASH_MODEL = os.getenv("GEMINI_FLASH_MODEL", "gemini-2.5-flash")


def generate_gemini_content(
    prompt: str,
    system_instruction: Optional[str] = None,
    tools: Optional[List[Dict[str, Any]]] = None,
    model: Optional[str] = None,
    temperature: float = 0.2,
    max_output_tokens: int = 2048,
    api_key: Optional[str] = None
) -> Dict[str, Any]:
    """
    Invoke Google Gemini API with system instructions, tools, and fallback handling.
    Returns structured dictionary with generated text or tool calls.
    """
    key = api_key or GEMINI_API_KEY
    chosen_model = model or GEMINI_MODEL

    if not key:
        return {
            "success": False,
            "text": "",
            "is_fallback": True,
            "error": "GEMINI_API_KEY not configured. Running in offline rule-based diagnostic engine."
        }

    endpoint = f"https://generativelanguage.googleapis.com/v1beta/models/{chosen_model}:generateContent?key={key}"

    payload: Dict[str, Any] = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {
            "temperature": temperature,
            "maxOutputTokens": max_output_tokens
        }
    }

    if system_instruction:
        payload["systemInstruction"] = {
            "parts": [{"text": system_instruction}]
        }

    if tools:
        payload["tools"] = tools

    try:
        req = urllib.request.Request(
            endpoint,
            data=json.dumps(payload).encode("utf-8"),
            headers={"Content-Type": "application/json"}
        )
        with urllib.request.urlopen(req, timeout=20) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            candidates = data.get("candidates", [])
            if not candidates:
                return {
                    "success": False,
                    "text": "No response candidate generated by Gemini.",
                    "is_fallback": True
                }

            first_candidate = candidates[0]
            parts = first_candidate.get("content", {}).get("parts", [])
            
            # Check for function/tool call
            for part in parts:
                if "functionCall" in part:
                    return {
                        "success": True,
                        "tool_call": part["functionCall"],
                        "is_fallback": False
                    }

            combined_text = "".join(p.get("text", "") for p in parts)
            return {
                "success": True,
                "text": combined_text,
                "is_fallback": False
            }

    except Exception as e:
        return {
            "success": False,
            "text": "",
            "is_fallback": True,
            "error": f"Gemini API request failed: {str(e)}"
        }
