apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-service
  namespace: kumarh5149-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member-service
  template:
    metadata:
      labels:
        app: member-service
    spec:
      containers:
        - name: member-service
          image: 794558722040.dkr.ecr.us-east-1.amazonaws.com/member-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3005
          env:
            - name: PORT
              value: "3005"
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: members_db
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: insurance-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: insurance-secrets
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: kumarh5149-dev
  labels:
    app: member-service
spec:
  selector:
    app: member-service
  ports:
    - name: http
      protocol: TCP
      port: 3005
      targetPort: 3005
  type: ClusterIP
