global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:3001']

  - job_name: 'auth'
    static_configs:
      - targets: ['auth:3002']

  - job_name: 'policy-service'
    static_configs:
      - targets: ['policy-service:3003']

  - job_name: 'claim-service'
    static_configs:
      - targets: ['claim-service:3004']

  - job_name: 'member-service'
    static_configs:
      - targets: ['member-service:3005']

  - job_name: 'billing-service'
    static_configs:
      - targets: ['billing-service:3006']

  - job_name: 'hospital-service'
    static_configs:
      - targets: ['hospital-service:3008']

  - job_name: 'document-service'
    static_configs:
      - targets: ['document-service:3009']

  - job_name: 'support-service'
    static_configs:
      - targets: ['support-service:3010']
