apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "healthshield.fullname" . }}-postgres-init
  labels:
    {{- include "healthshield.labels" . | nindent 4 }}
data:
  10-create-databases.sh: |-
{{ .Files.Get "files/init/10-create-databases.sh" | indent 4 }}
  20-init-schema.sql: |-
{{ .Files.Get "files/init/20-init-schema.sql" | indent 4 }}
