{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "healthshield.fullname" . }}-secrets
  labels:
    {{- include "healthshield.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.database.user | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
  POSTGRES_USER: {{ .Values.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
  JIRA_BASE_URL: {{ .Values.integrations.jira.baseUrl | quote }}
  JIRA_USER_EMAIL: {{ .Values.integrations.jira.email | quote }}
  JIRA_API_TOKEN: {{ .Values.integrations.jira.apiToken | default "PLACEHOLDER_TOKEN" | quote }}
  LOKI_PUSH_URL: {{ .Values.integrations.loki.pushUrl | quote }}
  AWS_S3_KAFKA_BUCKET: {{ .Values.integrations.s3.kafkaBucket | quote }}
  AWS_S3_DOCUMENTS_BUCKET: {{ .Values.integrations.s3.documentsBucket | quote }}
{{- end }}
