apiVersion: v1
kind: Secret
metadata:
  name: insurance-secrets
  namespace: health-insurance
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres123
  JWT_SECRET: health-insurance-secret-key-2026
